development:
  access_key_id: AKIAJS5ROQQ4MS3HR6XQ
  secret_access_key: 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

production:
  access_key_id: AKIAJS5ROQQ4MS3HR6XQ
  secret_access_key: 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